# Generated by Django 4.0.2 on 2025-02-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_story_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='core.comment'),
        ),
        migrations.AddField(
            model_name='story',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='stories', to='core.Tag'),
        ),
    ]
