# Generated by Django 4.0.2 on 2025-02-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe_category_recipe_comment_recipe_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='story',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.story'),
        ),
    ]
